// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_DpRW3xQy6maVz6MADD5tAP1p0lnAfs',
    appId: '1:342826597987:web:82250c6010223152f80256',
    messagingSenderId: '342826597987',
    projectId: 'reklamizlekazan-8db84',
    authDomain: 'reklamizlekazan-8db84.firebaseapp.com',
    storageBucket: 'reklamizlekazan-8db84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASg6B9goIamAWs-wFbeQQfscpZgysIJr4',
    appId: '1:342826597987:android:760c050f3e39c459f80256',
    messagingSenderId: '342826597987',
    projectId: 'reklamizlekazan-8db84',
    storageBucket: 'reklamizlekazan-8db84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Lif-FoBOTcMQDimr-7h1XMKZZQBHbEU',
    appId: '1:342826597987:ios:ddde7a3dcc51879df80256',
    messagingSenderId: '342826597987',
    projectId: 'reklamizlekazan-8db84',
    storageBucket: 'reklamizlekazan-8db84.appspot.com',
    iosClientId: '342826597987-ojvdn4kjrhb71cfgql1pv3673halat4g.apps.googleusercontent.com',
    iosBundleId: 'com.eapp.reklamizlekazan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Lif-FoBOTcMQDimr-7h1XMKZZQBHbEU',
    appId: '1:342826597987:ios:ddde7a3dcc51879df80256',
    messagingSenderId: '342826597987',
    projectId: 'reklamizlekazan-8db84',
    storageBucket: 'reklamizlekazan-8db84.appspot.com',
    iosClientId: '342826597987-ojvdn4kjrhb71cfgql1pv3673halat4g.apps.googleusercontent.com',
    iosBundleId: 'com.eapp.reklamizlekazan',
  );
}
